[package]
name = "udt"
version.workspace = true
edition.workspace = true

[dependencies]
udt-sys = { path = "./udt-sys" }
os_socketaddr = "0.2"
tokio = { version = "1.47", features = ["rt"] }
futures = "0.3"
cfg-if = "1"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["ws2def"] }
