[package]
name = "udt-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
bytes = "1"
arbitrary = { version = "1", features = ["derive"] }
udt-proto = { path = "../udt-proto", features = ["fuzzing"] }

[[bin]]
name = "decode"
path = "fuzz_targets/decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "connection"
path = "fuzz_targets/connection.rs"
test = false
doc = false
bench = false

[[bin]]
name = "listener"
path = "fuzz_targets/listener.rs"
test = false
doc = false
bench = false
