[package]
name = "udt-async"
version.workspace = true
edition.workspace = true

[features]
tokio = ["dep:tokio"]
async-io = ["dep:async-io", "dep:futures-lite", "dep:async-channel"]

[dependencies]
udt-proto = { path = "../udt-proto" }
bytes = "1"
rand = "0.9"

tokio = { version = "1", features = ["net", "time", "sync", "rt", "rt-multi-thread", "macros"], optional = true }
socket2 = "0.6"

async-io = { version = "2", optional = true }
futures-lite = { version = "2", optional = true }
async-channel = { version = "2", optional = true }
