[package]
name = "udt-cpp-interop-tests"
version.workspace = true
edition.workspace = true

[dev-dependencies]
udt-async = { workspace = true }
udt-compat = { path = "../udt-compat" }
tokio = { version = "1", features = ["full"] }
bytes = "1"
futures = { version = "0.3", default-features = false, features = ["executor"] }
